10gen/docs-shared

shared-content-ref-test/ref-test.rst
testing feasibility of dynamic refs
=> ref testing

server/platform-support/platform-support.rst
Jira:
https://jira.mongodb.org/browse/DOCS-15239
Description:
Adding 5.0.9 to support for RHEL 9 s390x Enterprise.
=> DOCS-15239 5.0.9 -> RHEL 8 s390x

server/platform-support/platform-support.rst
This reverts commit c685f5a38ef9161511786b79b9df8b32a685c8ec.
=> Revert "(DOCS-15647): Update server platform support for RHEL 9 (#34)"

server/platform-support/platform-support.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-31811)
[SERVER] Remove 4.2 from the supported platforms list
=> DOCSP-31811 clean up 4.2

dbx/lifecycle-schedule-callout.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-30911)
=> DOCSP-30911: add server support callout

dbx/issues-and-help.rst
JIRA: https://jira.mongodb.org/browse/DOCSP-34427
This page can be shared by using the sharedinclude directive and appropriate replacements.
Please check the copy for any issues/improvements.
=> DOCSP-34427: content reuse prototype page

dbx/connection-troubleshooting.rst
Changes:
- Add the anchor placeholder to test whether Snooty associates the title and anchor in this format (did not recognize association between the non-placeholder anchor and the title)
- Moved a placeholder from inline context to block context since the content was block content.
=> DOCSP-34709: Updates to fix issues

dbx/encrypt-fields.rst
Changes follow from edits proposed in https://github.com/mongodb/docs-rust/pull/98/.
=> improve encryption content

cet/procedures/fed-auth-okta.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-35985)
Shared inclusion for [this PR](https://github.com/10gen/docs-cloud-manager/pull/29)
=> (DOCSP-35985) Set up shared include for Okta fed auth steps

cet/procedures/fed-auth-okta-credentials.rst, cet/procedures/fed-auth-okta-finalize.rst, cet/procedures/fed-auth-okta-saml.rst
[JIRA](https://jira.mongodb.org/browse/DOCSP-35985)
Follow up work from #69.
Includes for [this PR](https://github.com/10gen/docs-cloud-manager/pull/29)
=> DOCSP 35985

dbx/connection-troubleshooting.rst
Changes:
- Grammar update 
- Placeholder for a percent-encode example.
=> 020724: Tweaks to connection troubleshooting page

server/platform-support/platform-support.rst
##DESCRIPTION
Update platform support matrix 8.0
##JIRA
https://jira.mongodb.org/browse/DOCSP-38731
##STAGING & BUILD LOG
No staging or build log.
Rst rendering of updated table
https://github.com/10gen/docs-shared/blob/eeb25384dff9dd78c1897a1bad7ee701c769ea04/server/platform-support/platform-support.rst
=> DOCSP-38731 Update platform support matrix 8.0

dbx/jvm-validate-artifacts.rst
Adds content to be included on JVM driver docs
https://jira.mongodb.org/browse/DOCSP-39555
No staging until it is included
=> DOCSP-39555: java driver sig verification

dbx/jvm/v5.2-wn-items.rst
https://jira.mongodb.org/browse/DOCSP-41474
Adds an item to the v5.2 whats new
=> DOCSP-41474: fips compliance for jvm drivers

dbx/jvm/v5.2-wn-items.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-38784
=> DOCSP-38784: Sharded cluster retries

dbx/jvm/v5.2-wn-items.rst
[DOCSP-40414](https://jira.mongodb.org/browse/DOCSP-40414)
=> DOCSP-40414: jvm crypto improvement

dbx/jvm/v5.3-wn-items.rst
Adds an entry to JVM 5.3 whats new
https://jira.mongodb.org/browse/DOCSP-45802
=> DOCSP-45802: remove fairness cxn pool jvm 5.3

dbx/jvm/v5.3-wn-items.rst
https://jira.mongodb.org/browse/DOCSP-46643
=> DOCSP-46643: JVM future minor release dropping 4.0

dbx/docker-replica-set.rst
Create note about how to connect to a replica set in Docker containers
=> DOCSP-47829 - Replica set in Docker

dbx/jvm/v5.4-wn-items.rst
https://jira.mongodb.org/browse/DOCSP-48104
=> DOCSP-48104 - Atlas search queries operators release notes

dbx/extended-json.rst
https://jira.mongodb.org/browse/DOCSP-49078
=> Add extended JSON boilerplate

dbx/jvm/v5.5-wn-items.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-49765
=> DOCSP-49765: 5.5 performance improvements

dbx/agg-tutorials-manual-tip.rst
https://jira.mongodb.org/browse/DOCSP-50745
Creates a shared admonition to add to the different driver docs.
=> DOCSP-50745: shared tip for agg tutorials link

dbx/connection-troubleshooting.rst
Jira: https://jira.mongodb.org/browse/DOCSP-51671
=> DOCSP-51671-connection-troubleshooting

dbx/kubernetes-oidc-token.rst
Jira
----
https://jira.mongodb.org/browse/DOCSP-51993
=> DOCSP-51993 fix shared

dbx/help-links.rst
Jira: https://jira.mongodb.org/browse/DOCSP-53484
=> DOCSP-53484 Update Forum link wording

cet/atlas/data-processing.rst
[Jira](https://jira.mongodb.org/browse/DOCSP-54109)
=> Adds deprecation note per Legal.
