- dbx/about-compatibility.rst
This adds a shared page for use in dedicated driver projects (Node, Go, Java)
> add common about info for driver compat tables

- cet/atlas/supported-browsers.rst
Extracted the existing table from [this Atlas page](https://docs.atlas.mongodb.com/reference/supported-browsers/) to use in guides.
> atlas supported browsers

- .vscode/settings.json
- server/platform-support/platform-support.rst
Add platform support for Amazon Linux 2022 
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/v6.0/installation/#supported-platforms
https://jira.mongodb.org/browse/DOCS-15888
No build log because this is `docs-shared` repo
> DOCS-15888 Amazon Linux 2022 Support

- server/platform-support/platform-support.rst
Original ticket asks to update Ubuntu 22.04 arm64 entry to be compatible starting in 6.0.4, not 6.0.3. The correct entry already existed, so it looks like it was incorrectly duplicated. 
This removes the incorrect entry. Correct entry can be found on lines 526 and 535.
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/platform-support-testing/administration/production-notes/#platform-support-matrix
https://jira.mongodb.org/browse/DOCSP-29005
> DOCSP-29005 Remove incorrect arm64 Ubuntu Platform entry

- dbx/encrypt-fields.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-26903
Moving [content](https://github.com/mongodb/docs-golang/blob/master/source/fundamentals/encrypt-fields.txt) from the Golang docs repo to this repo
> DOCSP-26903: move encrypt fields page

- server/platform-support/platform-support.rst
Removes v6.0 support for RHEL/CentOS 7 on platform support matrix. 
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/platform-support-testing/installation/#:~:text=Community-,RHEL/CentOS%207,-ppc64le
https://jira.mongodb.org/browse/DOCSP-29471
> DOCSP-29471 Remote RHEL/CentOS 7 6.0 from Support Matrix

- .vscode/settings.json
- server/platform-support/platform-support.rst
- Add RHEL9 arm64 to platform support matrix 
https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/platform-support-testing/installation/#:~:text=4.2.13%2B-,RHEL/CentOS/Rocky/Alma%209,-arm64
https://jira.mongodb.org/browse/DOCS-15147
> DOCS-15147 Add RHEL9 ARM

- server/platform-support/platform-support.rst
Notes that RHEL/CentOS 7 support is added from v6.0.7+
N/A for `docs-shared` repo. 
https://jira.mongodb.org/browse/DOCSP-31054
N/A for `docs-shared` repo.
> DOCSP-31054 RHEL/CentOS 7 ppc64le 6.0.7 Support

- server/platform-support/platform-support.rst
There is no way to stage shared repo builds. I used the contents of the sharedinclude to create a fake include and generate a server build instead. 
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/docs/docsworker-xlarge/DOCSP-31278-oracle-compat-matrix-v7.0/administration/production-notes/#platform-support-matrix
)
[JIRA](https://jira.mongodb.org/browse/DOCSP-31278)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d0ff3f67dbe9101096364b)
[FAKE STAGING PR](https://github.com/10gen/docs-mongodb-internal/pull/4287)
> DOCSP-31278 Oracle warning

- dbx/connection-troubleshooting.rst
JIRA:
https://jira.mongodb.org/browse/DOCSP-34709
Note for the reviewer:
This uses the [Rust](https://www.mongodb.com/docs/drivers/rust/current/connection-troubleshooting/) version as a starting point. A few writing and info accuracy fixes were incorporated.
Currently unknown whether the anchors can be used in replacement directives. Any issues discovered during testing will be addressed in a followup PR.
> DOCSP-34709: Shared Content Connection Troubleshooting page

- dbx/connection-troubleshooting.rst
Description:
Removed the title from the shared page since Snooty needs to pair it with the page anchor. While the replacement functions properly, Snooty also reports an indentation error and ambiguous reference error.
> DOCSP-34709: remove title from shared page

- dbx/atlas-connect-compatible-deployment.rst
This enables us to use consistent wording and make any necessary updates in one place for the Atlas CTA featured in select driver documentation pages.
> Convert Atlas CTA for driver docs into shared content

- dbx/issues-and-help.rst
Fix to the manual link text (requires a title).
> Fix manual link format

- server/platform-support/platform-support.rst
Removes CentOS Stream from RHEL 8/9 compatibility table rows for Server
[Jira Ticket](https://jira.mongodb.org/browse/DOCSP-35185)
While the autobuilder and staging do not work in this repo, I staged via copy/paste in the Server docs. You can see the content rendered here: https://preview-mongodbsarahsimpers.gatsbyjs.io/docs/install-page-test/installation/#supported-platforms
> (DOCSP-35185) Removes CentOS Stream

- server/platform-support/platform-support.rst
- Adding `Ubuntu 24.04` to PS matrix
Note- Builds not enabled for this repo, no build log available. See staged changes here: https://github.com/10gen/docs-mongodb-internal/pull/8404
https://jira.mongodb.org/browse/DOCSP-41493
> DOCSP-41493-add-ubuntu-24-04-support

- server/platform-support/platform-support.rst
Update the platform support matrix for macOS 14 support. Support information sourced from the [Platform Roadmap Spreadsheet](https://docs.google.com/spreadsheets/d/1-sZKW70HbVt2yHOWa18qwBwi-gBcn54tWmronnn89kI/edit?gid=1790519872#gid=1790519872).
See the rendered rst version of the support matrix: https://github.com/10gen/docs-shared/blob/ebfb60c1f5e1cb36fab1bd37b989da56e041983b/server/platform-support/platform-support.rst
> DOCSP-38877-macOS-14-support

- dbx/jvm/v5.2-wn-items.rst
https://jira.mongodb.org/browse/DOCSP-38279
Adds an entry for JVM v5.2 release. will be included in the whats new pages for all 5 drivers.
> DOCSP-38279: graalvm metadata

- dbx/jvm/v5.2-wn-items.rst
https://jira.mongodb.org/browse/DOCSP-42281
describes the API changes to vectorsearchoptions
> DOCSP-42281: vectorsearch options

- dbx/encrypt-fields.rst
- dbx/jvm/v5.2-wn-items.rst
https://jira.mongodb.org/browse/DOCSP-43906
next steps:
add the link to whats new and driver content to the JVM drivers pages to describe the version of `mongodb-crypt` needed for that driver version.
> DOCSP-43906: crypto versioning revision

- dbx/causal-consistency.rst
Since causal consistency is not driver-specific, we can reuse the description across repos. The copy was taken from the [Java PR](https://github.com/mongodb/docs-java/pull/623) and tech approved in [PyMongo](https://github.com/mongodb/docs-pymongo/pull/188).
> Add duplicate causal consistency info

- dbx/srv-polling.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-47044
Copied from the [PyMongo section](https://github.com/mongodb/docs-pymongo/pull/186) on DNS SRV records
> DOCSP-47044: Polling DNS SRV records

- dbx/jvm/atlas-search-operator-helpers.rst
https://jira.mongodb.org/browse/DOCSP-48104
Changes per: https://github.com/mongodb/docs-kotlin-sync/pull/87
> [DBX] JVM SearchOperators helper methods tweaks

- dbx/causal-consistency.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-48660
> DOCSP-48660: Causal consistency edits

- cet/atlas/data-processing.rst
Serverless instances are removed fully. This doc mentions them. Serverless are replaced by Flex. 
I changed one reference. 
This change is needed because [this PR](https://github.com/10gen/docs-mongodb-internal/pull/13283) removed a replacement {+Serverless-instances+} that this file was using. 
I can't add Anurag as a reviewer for this repo. 
I can:
remove this sentence altogether, as serverless are not supported anymore. 
replace serverless with Flex if that's approved (I am not aware of any limitations in this area, but we should confirm.
What do you suggest?
Note: this change is needed ONLY because it breaks the build for the linked PR. 
Thank you.
> (DOCSP-45160) Replace a replacement for Serverless with Flex, no content changes

- dbx/jvm/v5.6-wn-items.rst
Questions for technical reviewers:
- Is the page accurate?
- Does the page omit any important, user-facing changes?
- Does the page include any internal changes that aren't relevant to users?
- This page is shared across all JVM drivers; do all changes apply to all JVM drivers?
https://jira.mongodb.org/browse/DOCSP-53883
No staging available
> DOCSP-53883 - JVM 5.6 shared release notes
